[common]
url = "https://developers.google.com/static/crawling/ipranges/common-crawlers.json"
pattern = "prefixes.*.*"

[special]
url = "https://developers.google.com/static/crawling/ipranges/special-crawlers.json"
pattern = "prefixes.*.*"

[user_triggered_fetchers]
url = "https://developers.google.com/static/crawling/ipranges/user-triggered-fetchers.json"
pattern = "prefixes.*.*"

[user_triggered_fetchers_google]
url = "https://developers.google.com/static/crawling/ipranges/user-triggered-fetchers-google.json"
pattern = "prefixes.*.*"

[user_triggered_agents]
url = "https://developers.google.com/static/crawling/ipranges/user-triggered-agents.json"
pattern = "prefixes.*.*"
