#!/usr/bin/env python3
"""Build script for generating fresh bundled whitelists for Heavy."""

from dataclasses import dataclass, field
import datetime
import json
import sys
import tomllib
from typing import Any
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"
DIST = ROOT / "dist"

# Map of which source files are built into which bundles
BUNDLES = {
    "base": [
        "base",
    ],
    "crawlers": [
        "apple",
        "bing",
        "commoncrawl",
        "duckduckgo",
        "google-common",
        "google-special",
        "internet-archive",
        "kagi",
        "marginalia",
        "mojeekbot",
        "qwant",
        "wikimedia-citoid",
        "yandex",
    ],
    "user-triggered": [
        "google-user-triggered-fetchers-google",
        "google-user-triggered-agents",
    ],
}


@dataclass
class Whitelist:
    path: Path
    cidrs: list[str] = field(default_factory=list)
    paths: list[str] = field(default_factory=list)


def main():
    # Make sure all input files are accounted for
    src_stems = {p.stem for p in SRC.glob("*.toml")}
    required_stems = {stem for bundle in BUNDLES.values() for stem in bundle}
    if len(required_stems - src_stems) > 0:
        sys.exit(f"error: missing input files: {required_stems - src_stems}")
    if len(src_stems - required_stems) > 0:
        print(
            f"warning: unused src files: {src_stems - required_stems}", file=sys.stderr
        )

    # Build individual whitelists for each input file
    start = datetime.datetime.now(tz=datetime.UTC)
    whitelists: dict[str, Whitelist] = {}
    for stem in sorted(required_stems):
        src_path = SRC / f"{stem}.toml"
        whitelists[stem] = build_whitelist(src_path)

    # Build whitelist bundles and write them to disk
    DIST.mkdir(exist_ok=True)
    for bundle_stem, src_stems in BUNDLES.items():
        parts = [whitelists[stem] for stem in src_stems]
        with open(DIST / f"{bundle_stem}.toml", "w") as f:
            f.write(f"# Whitelist bundle generated by {Path(__file__)}\n")
            f.write(f"# Generated at: {start.isoformat(timespec='seconds')}\n   ")
            f.write(format_bundle(parts))


def build_whitelist(path: Path) -> Whitelist:
    """Load a single Whitelist from static rules and/or an online CIDR list."""
    result = Whitelist(path)

    # Read definition from disk
    with open(path, "rb") as f:
        src = tomllib.load(f)

    # Load static rules
    if "cidrs" in src:
        result.cidrs.extend(src["cidrs"])
    if "paths" in src:
        result.paths.extend(src["paths"])

    # Derive CIDRs from latest published JSON
    if "url" in src and "pattern" in src:
        data = fetch_json(src["url"])
        result.cidrs.extend(lookup_strings(data, src["pattern"]))

    return result


def format_bundle(whitelists: list[Whitelist]) -> str:
    """Produce a combined TOML whitelist for Heavy, grouping sub-whitelists by name."""

    lines = []

    def put_group(stem: str, values: list[str]):
        lines.append(f"  # {stem}")
        for v in values:
            # Mild hack: use JSON to escape strings because the rules are almost exactly the same as
            # TOML's. Earlier versions of the TOML spec explicitly call this out: "You may notice
            # that the above string specification is the same as JSON's string definition," from
            # https://toml.io/en/v0.3.1#string.
            lines.append(f"  {json.dumps(v)},")

    def put_grouped_array(key: str, groups: dict[str, list[str]]):
        if len(groups) == 0:
            return
        lines.append("")
        lines.append(f"{key} = [")
        for i, (stem, group) in enumerate(groups.items()):
            if i > 0:
                lines.append("")
            put_group(stem, group)
        lines.append(f"]")

    # Split the different patterns apart by data type: CIDRs vs. path regexes
    cidrs: dict[str, list[str]] = {}
    paths: dict[str, list[str]] = {}
    for whitelist in whitelists:
        name = str(whitelist.path.relative_to(ROOT))
        if len(whitelist.cidrs) > 0:
            cidrs[name] = whitelist.cidrs
        if len(whitelist.paths) > 0:
            paths[name] = whitelist.paths

    # Write arrays for each data type
    put_grouped_array("cidrs", cidrs)
    put_grouped_array("paths", paths)
    return "\n".join(lines) + "\n"


def fetch_json(url: str) -> dict[str, Any]:
    """Download and parse JSON from a web URL."""
    print(f"  fetching {url}")
    res = urllib.request.urlopen(url)
    return json.loads(res.read().decode("utf-8"))


def lookup_strings(data: dict[str, Any], pattern: str) -> list[str]:
    """Given a nested JSON structure, extract string values matching a path pattern.

    Path patterns support very simple globbing: they look like "foo.bar.baz" or "foo.*.baz", where
    "*" is a single-level wildcard. This flexibility might be overkill, because every CIDR JSON I've
    seen so far follows the same format.
    """
    parts = pattern.split(".")
    result: list[str] = []

    def recurse(node, i: int):
        if isinstance(node, str):
            if i == len(parts):
                result.append(node)
        elif isinstance(node, dict):
            for k, v in node.items():
                if parts[i] == "*" or parts[i] == k:
                    recurse(v, i + 1)
        elif isinstance(node, list):
            for idx, v in enumerate(node):
                if parts[i] == "*" or int(parts[i]) == idx:
                    recurse(v, i + 1)

    recurse(data, 0)
    return result


if __name__ == "__main__":
    main()
